version: "3"
services:
  postgres:
    image: postgres:12
    user: "${AIRFLOW_UID}:${AIRFLOW_GID}"
    volumes:
      - ./pg-airflow:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5435:5432"
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: webserver
    restart: always
    depends_on:
      - postgres
    command: webserver
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./ssh:/home/airflow/.ssh
      - ./requirements.txt:/opt/airflow/requirements.txt
    ports:
      - "8045:8080"
      - "8745:8793"
    entrypoint: ./scripts/airflow-entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 32
